databases:
  - name: vietqr-db
    plan: free
    databaseName: vietqr
    user: vietqr

services:
  - type: web
    name: vietqr-backend
    plan: free
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx tsc && npx prisma db push && npx prisma db seed
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vietqr-db
          property: connectionString
