databases:
  - name: vietqr-db
    plan: free
    databaseName: vietqr
    user: vietqr

services:
  - type: web
    name: vietqr-backend
    plan: free
    runtime: node
    buildCommand: npm install && npm run build && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vietqr-db
          property: connectionString
